version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # - pip install --upgrade pip
      # - pip install --upgrade awscli aws-sam-cli
      # - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - export AWS_DEFAULT_REGION=us-east-1
      - export AWS_ACCOUNT_ID=652052937334
      # - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - ls -al
      - pwd
      - export BUCKET=dev-cloudeng-lambda-pl-bucket-max
      - aws ecr-public get-login-password  | docker login --username AWS --password-stdin public.ecr.aws
      - sam build
      # - sam package --image-repository 652052937334.dkr.ecr.us-east-1.amazonaws.com/sam-test:latest --template-file template.yml --output-template-file outputtemplate.yml --s3-bucket $BUCKET
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - sam package --image-repository 652052937334.dkr.ecr.us-east-1.amazonaws.com/sam-test --output-template-file outputtemplate.yml --s3-bucket $BUCKET
      - sam deploy --template-file ./outputtemplate.yml --stack-name sam-dep-test-1 --capabilities CAPABILITY_IAM --image-repository 652052937334.dkr.ecr.us-east-1.amazonaws.com/sam-test
      # - sam package --s3-bucket $BUCKET --output-template-file outputtemplate.yml

artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml