AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  test-lambda-deploy-typescript

  Sample SAM Template for test-lambda-deploy-typescript
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: 'test-codepl-lambda-nodejs-sample2'
      Description: test lambda sam codepl
      PackageType: Image
      ImageUri: 652052937334.dkr.ecr.us-east-1.amazonaws.com/ecr-test
      # CodeUri: src/
      # Handler: app.lambdaHandler
      # Runtime: nodejs12.x
      Architectures:
        - x86_64
    Metadata:
      DockerTag: latest
      DockerContext: ./src
      Dockerfile: dockerfile
